#!/usr/bin/env python3
"""SYSU_AIOTOS runtime bundle helpers."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BUNDLE_DIR = ROOT / "runtime_bundle"


def _bundle_paths(bundle_dir: Path) -> list[Path]:
    return sorted(path for path in bundle_dir.rglob("*") if path.is_file())


def _virtual_path(bundle_dir: Path, path: Path) -> str:
    return "/" + path.relative_to(bundle_dir).as_posix()


def _c_string_literal(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _bytes_literal(data: bytes) -> str:
    if not data:
        return ""
    return ", ".join(f"0x{byte:02x}" for byte in data)


def generate_bundle_header(bundle_dir: Path, output: Path) -> None:
    bundle_dir = bundle_dir.resolve()
    files = _bundle_paths(bundle_dir)
    auto_start_path = bundle_dir / "maixapp" / "auto_start.txt"
    app_id = "sysu_aiotos_demo"

    if auto_start_path.exists():
        raw = auto_start_path.read_text(encoding="utf-8").strip()
        if raw:
            app_id = raw

    app_script = f"/maixapp/apps/{app_id}/main.py"
    lines = [
        "/* Auto-generated by tools/runtime_bundle.py. */",
        "#ifndef MAIX_RUNTIME_BUNDLE_AUTOGEN_H",
        "#define MAIX_RUNTIME_BUNDLE_AUTOGEN_H",
        "",
        f"#define MAIX_RUNTIME_BUNDLE_AUTO_START_APP_ID {_c_string_literal(app_id)}",
        f"#define MAIX_RUNTIME_BUNDLE_AUTO_START_SCRIPT {_c_string_literal(app_script)}",
        f"#define MAIX_RUNTIME_BUNDLE_FILE_COUNT {len(files)}u",
        "",
    ]

    for index, path in enumerate(files):
        data = path.read_bytes()
        lines.append(f"static const unsigned char g_maix_bundle_data_{index}[] = {{")
        if data:
            lines.append(f"    {_bytes_literal(data)}")
        lines.append("};")
        lines.append("")

    lines.append("static const maix_bundle_file_t g_bundle_files[] = {")
    for index, path in enumerate(files):
        lines.append(
            "    {"
            f"{_c_string_literal(_virtual_path(bundle_dir, path))}, "
            f"g_maix_bundle_data_{index}, sizeof(g_maix_bundle_data_{index})"
            "},"
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def summarize_bundle(bundle_dir: Path) -> dict[str, object]:
    files = _bundle_paths(bundle_dir.resolve())
    total_bytes = sum(path.stat().st_size for path in files)
    return {
        "file_count": len(files),
        "total_bytes": total_bytes,
        "files": ["/" + path.relative_to(bundle_dir).as_posix() for path in files],
    }


def _copy_tree(src: Path, dst: Path) -> None:
    for path in sorted(src.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(src)
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)


def stage_runtime_bundle(
    *,
    app_dir: Path,
    bundle_dir: Path = DEFAULT_BUNDLE_DIR,
    model_path: Path | None = None,
    labels_path: Path | None = None,
    manifest_path: Path | None = None,
    app_id: str | None = None,
    reset_app: bool = False,
) -> None:
    app_dir = app_dir.resolve()
    bundle_dir = bundle_dir.resolve()

    if not app_dir.exists():
        raise FileNotFoundError(f"应用目录不存在: {app_dir}")

    resolved_app_id = app_id or app_dir.name
    app_target = bundle_dir / "maixapp" / "apps" / resolved_app_id

    if reset_app and app_target.exists():
        shutil.rmtree(app_target)

    app_target.mkdir(parents=True, exist_ok=True)
    _copy_tree(app_dir, app_target)

    auto_start = bundle_dir / "maixapp" / "auto_start.txt"
    auto_start.parent.mkdir(parents=True, exist_ok=True)
    auto_start.write_text(f"{resolved_app_id}\n", encoding="utf-8")

    if not (app_target / "main.py").exists():
        raise FileNotFoundError(f"应用入口缺失: {app_target / 'main.py'}")

    app_yaml = app_target / "app.yaml"
    if not app_yaml.exists():
        app_yaml.write_text(
            "\n".join(
                [
                    f"id: {resolved_app_id}",
                    f"name: {resolved_app_id}",
                    "version: 0.1.0",
                    "author: local",
                    "files:",
                    "  - main.py",
                    "",
                ]
            ),
            encoding="utf-8",
        )

    if model_path is not None:
        model_path = model_path.resolve()
        if not model_path.exists():
            raise FileNotFoundError(f"模型文件不存在: {model_path}")
        model_target = bundle_dir / "models" / model_path.name
        model_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(model_path, model_target)

    if labels_path is not None:
        labels_path = labels_path.resolve()
        if not labels_path.exists():
            raise FileNotFoundError(f"标签文件不存在: {labels_path}")
        labels_target = bundle_dir / "models" / labels_path.name
        labels_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(labels_path, labels_target)

    if manifest_path is not None:
        manifest_path = manifest_path.resolve()
        if not manifest_path.exists():
            raise FileNotFoundError(f"manifest 文件不存在: {manifest_path}")
        manifest_target = bundle_dir / "models" / "model.manifest"
        manifest_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(manifest_path, manifest_target)
    elif model_path is not None or labels_path is not None:
        manifest_target = bundle_dir / "models" / "model.manifest"
        manifest_target.parent.mkdir(parents=True, exist_ok=True)

        lines = ["task=classification"]
        if model_path is not None:
            lines.append(f"default={model_path.name}")
            if model_path.suffix == ".tflite":
                lines.append(f"tflite={model_path.name}")
            elif model_path.suffix == ".kmodel":
                lines.append(f"kmodel={model_path.name}")
        if labels_path is not None:
            lines.append(f"labels={labels_path.name}")

        manifest_target.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="SYSU_AIOTOS runtime bundle helper")
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="从 runtime_bundle 生成 C 头文件")
    gen.add_argument("--bundle-dir", default=str(DEFAULT_BUNDLE_DIR))
    gen.add_argument("--output", required=True)

    stage = sub.add_parser("stage", help="把 Python 应用和模型打包到 runtime_bundle")
    stage.add_argument("--app-dir", required=True)
    stage.add_argument("--bundle-dir", default=str(DEFAULT_BUNDLE_DIR))
    stage.add_argument("--model")
    stage.add_argument("--labels")
    stage.add_argument("--manifest")
    stage.add_argument("--app-id")
    stage.add_argument("--reset-app", action="store_true")

    info = sub.add_parser("info", help="查看当前 runtime_bundle 内容")
    info.add_argument("--bundle-dir", default=str(DEFAULT_BUNDLE_DIR))

    args = parser.parse_args()

    if args.command == "generate":
        generate_bundle_header(Path(args.bundle_dir), Path(args.output))
        print(f"[BUNDLE] generated {args.output}")
        return 0

    if args.command == "stage":
        stage_runtime_bundle(
            app_dir=Path(args.app_dir),
            bundle_dir=Path(args.bundle_dir),
            model_path=Path(args.model) if args.model else None,
            labels_path=Path(args.labels) if args.labels else None,
            manifest_path=Path(args.manifest) if args.manifest else None,
            app_id=args.app_id,
            reset_app=args.reset_app,
        )
        print(f"[BUNDLE] staged app into {args.bundle_dir}")
        return 0

    if args.command == "info":
        summary = summarize_bundle(Path(args.bundle_dir))
        print(f"[BUNDLE] files={summary['file_count']} bytes={summary['total_bytes']}")
        for path in summary["files"]:
            print(f"[BUNDLE] {path}")
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
